[destination.filesystem]
bucket_url = "s3://$AWS_S3_BUCKET" # replace with your bucket name,

[destination.filesystem.credentials]
aws_access_key_id = "$AWS_ACCESS_KEY_ID" # copy the access key here
aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY" # copy the secret access key here
endpoint_url = "$AWS_ENDPOINT_URL" # copy your endpoint URL here
